name: Upload assets with a release

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v11.19.10

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout        
        uses: actions/checkout@v2     
      # Zip Folders
      - name: Zip Folders
        run: |
          zip -r BesaResearch_Batches.zip . -x ".github/*" ".git/*"
      # Upload assets with a GitHub release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            BesaResearch_Batches.zip
